export default {
    1: "BCHBTC",
    2: "ETHBTC",
    3: "XRPBTC",
    6: "BTCUSDT",
    7: "ETHUSDT",
    8: "XRPUSDT",
    9: "XGTETH",
    12: "LTCBTC",
    13: "LTCUSDT",
    18: "XEMBTC",
    19: "ZECBTC",
    20: "ZECUSDT",
    21: "ZECETH",
    22: "XLMBTC",
    23: "XLMUSDT",
    25: "NADMETH",
};